server:
  port: 8080

cache:
  type: redis
  redis:
    host: localhost
    port: 6379

spring:
  datasource:
    url: jdbc:postgresql://${pg_write_db_host:localhost:5432}/${pg_db_name:product-service}
    username: ${pg_db_username:postgres}
    password: ${pg_db_password:Vaswik@2812}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


  profiles:
    active: local
  application:
    name: product-service


logging:
  level:
    org:
      hibernate:
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG
            StatementCreatorUtils: TRACE
  config: classpath:logback/logback-${spring.profiles.active}.xml

management:
  endpoints:
    web:
      exposure:
        include: "loggers, info, health"


inventory:
  service:
    url: http://localhost:8082/api/v1/inventory

